version: '3.7'
services:
  e2e:
    image: gcr.io/botfront-project/cypress-runner
    volumes:
      - ./botfront:/app
      - ./botfront/cypress:/app/cypress
      - ./botfront/cypress.json:/app/cypress.json
    depends_on: 
      - botfront
    env_file:
      - .env.cypress

  botfront:
    image: 'gcr.io/botfront-project/botfront:e2e'
    container_name: botfront-app
    restart: always
    # volumes:
    #   - './models/:/app/models'
    ports:
      - '8888:3000'
    depends_on:
      - mongo
    env_file:
      - .env.cypress
    environment:
      PORT: 3000
  # botfront-api:
  #   image: 'botfront/botfront-api:v0.15.1'
  #   container_name: botfront-api
  #   networks:
  #     - botfront-network
  #   restart: always
  #   depends_on:
  #     - mongo
  #   ports:
  #     - '8080:8080'
  #   env_file:
  #     - .env
  # rasa:
  #   image: 'botfront/rasa-for-botfront:v1.1.5-b3'
  #   container_name: botfront-rasa
  #   networks:
  #     - botfront-network
  #   restart: always
  #   ports:
  #     - '5005:5005'
  #   depends_on:
  #     - botfront-api
  #   volumes:
  #     - './models/:/app/models'
  #   command:
  #     - run
  #     - '--enable-api'
  #     - '--debug'
  #   env_file:
  #     - .env
  # actions:
  #   image: 'botfront/actions-sdk:latest'
  #   container_name: botfront-actions
  #   networks:
  #     - botfront-network
  #   restart: always
  #   ports:
  #     - '5055:5055'
  #   volumes:
  #     - './actions:/app/actions'
  #   env_file:
  #     - .env
  # duckling:
  #   image: 'botfront/duckling:latest'
  #   container_name: botfront-duckling
  #   networks:
  #     - botfront-network
  #   restart: always
  #   ports:
  #     - '8000:8000'
  mongo:
    image: 'mongo:latest'
    container_name: botfront-mongo
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env.cypress

