###########################################
# This docker-compose file is only for CI #
###########################################

version: '3.7'
services:
  e2e:
    image: gcr.io/botfront-project/cypress-runner:latest
    container_name: e2e
    volumes:
      - ../cypress.json:/app/cypress.json
      - ../cypress:/app/cypress
      - ../imports/lib:/app/imports/lib
      - ../imports/api:/app/imports/api
      - ./mounted/models/:/app/models
    depends_on:
      - botfront
    environment:
      - BOTFRONT_HOST=botfront:3000
      - CYPRESS_baseUrl=http://botfront:3000
      - CYPRESS_RASA_URL=http://rasa:5005
      - CYPRESS_RETRIES=2

  botfront:
    image: botfront-local
    container_name: botfront-test-app
    restart: always
    volumes:
      - './mounted/models/:/app/models'
    # ports:
    #   - '8888:3000'
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - BF_PROJECT_ID=bf
      - NODE_ENV=test
      - MONGO_URL=mongodb://mongo:27017/bf
      - ORCHESTRATOR=docker-compose
      - ROOT_URL=http://botfront:3000

  botfront-api:
    image: botfront-api-local
    container_name: botfront-test-api
    restart: always
    depends_on:
      - mongo
    # ports:
    #   - '8080:8080'
    environment:
      # NODE_ENV must not be set to test because it would use the mongo mem server which we don't want here
      - MONGO_URL=mongodb://mongo:27017/bf

  rasa:
    image: botfront/rasa-for-botfront:v1.3.9-bf.1
    container_name: botfront-test-rasa
    restart: always
    command:
      - run
      - --enable-api
    # ports:
    #   - '5005:5005'
    depends_on:
      - 'botfront-api'
    volumes:
      - './mounted/models/:/app/models'
    environment:
      - BF_URL=http://botfront-api:8080
      - BF_PROJECT_ID=bf

  # actions:
  #   image: 'botfront/actions-sdk:latest'
  #   container_name: botfront-test-actions
  #   networks:
  #     - botfront-network
  #   restart: always
  #   ports:
  #     - '5055:5055'
  #   volumes:
  #     - './actions:/app/actions'
  #   env_file:
  #     - .env
  # duckling:
  #   image: 'botfront/duckling:latest'
  #   container_name: botfront-test-duckling
  #   networks:
  #     - botfront-network
  #   restart: always
  #   ports:
  #     - '8000:8000'
  mongo:
    image: 'mongo:latest'
    container_name: botfront-test-mongo
    restart: always
    # ports:
    #   - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=bf
