###########################################
# This docker-compose file is only for CI #
###########################################

version: '3.7'
services:
  e2e:
    ipc: host # https://github.com/cypress-io/cypress/issues/350
    shm_size: 512M # https://github.com/cypress-io/cypress/issues/350#issuecomment-353572782
    image: cypress/included:5.6.0
    container_name: e2e
    volumes:
      - ../cypress.json:/app/cypress.json
      - ../cypress:/app/cypress
      - ../imports/lib:/app/imports/lib
      - ../imports/api:/app/imports/api
      - ./mounted/models:/app/models
    entrypoint: /bin/bash
    command:
      - -c
      - "npm install -C ./cypress && npx cypress run"
    working_dir: /app
    depends_on:
      - botfront
    environment:
      - CYPRESS_MODE=CI_RUN
      - CYPRESS_baseUrl=http://botfront:3000
      - CYPRESS_RASA_URL=http://rasa:5005
      - CYPRESS_RETRIES=5
      - CYPRESS_VIDEO=false
      - CYPRESS_SCREENSHOTS=true
      - CYPRESS_abort_strategy=spec
      - CYPRESS_GITHUB_TEMPLATE_REPO=${GITHUB_TEMPLATE_REPO}
      - CYPRESS_GITHUB_TOKEN=${GITHUB_TOKEN}

  botfront:
    image: botfront-local
    container_name: botfront-test-app
    restart: always
    volumes:
      - './mounted/models/:/app/models'
    # ports:
    #   - '8888:3000'
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - BF_PROJECT_ID=bf
      - MODE=test
      - MONGO_URL=mongodb://mongo:27017/bf
      - ROOT_URL=http://botfront:3000

  rasa:
    image: botfront/rasa-for-botfront:${RASA_TAG}
    container_name: botfront-test-rasa
    restart: always
    command:
      - -c
      - "rasa run --enable-api --debug"
    # ports:
    #   - '5005:5005'
    depends_on:
      - botfront
    volumes:
      - './mounted/models/:/app/models'
    environment:
      - BF_URL=http://botfront:3000/graphql
      - BF_PROJECT_ID=bf

  mongo:
    image: 'mongo:latest'
    container_name: botfront-test-mongo
    restart: always
    # ports:
    #   - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=bf
